images_dir: "C:/Users/penda/Documents/Study Materials/Image Processing/PROJECT/PROJECT DATASET/data/images"
masks_dir: "C:/Users/penda/Documents/Study Materials/Image Processing/PROJECT/PROJECT DATASET/data/masks"
save_dir: "C:/Users/penda/Documents/Study Materials/Image Processing/PROJECT/Nanoparticle-Segmentation/results"
